### ISSUE TITLE
[Declick] Remarques ergonomiques en vrac

### ISSUE THREAD

**Issue by ThomasTel** [colombbus/tangara-client#44]
-À la fin de "Apprendre - étape 4", on est laissé en plan.
-On ne nous explique pas qu'il faut toucher l'écran ou l'éditeur suivant que l'on veuille éditer ou non.
-La possibilité d'appuyer sur Ctrl + Espace pour la complétion n'est pas signalée.
-Mineur : sur http://www.declick.org/server/web/create#, 
quand on clique sur "Nous contacter" puis qu'on revient sur la page précédente, 
il n'y a plus de CSS.
-On ne nous suggère pas assez vivement de nous inscrire ou de nous logger,
causant une perte potentielle de données et donc de temps puisque
la progression n'est de ce fait pas prise en compte.
-Le garçon a des bras de bébés et les cuisses de Schwarzenegger.
-« Créer le garçon ou la fille :
ton prénom suivi de = new Héros() »
est assez maladroit.
-« Ajoute une action permettant d'avancer ce personnage de 350 pixels » est ambiguë.
On peut avoir l'impression que l'on nous demande de réaliser une nouvelle commande.
-L'alternance entre les phrases se finissant par des points et celles finissant sans est désagréable.
-« La programmation avec deux ailes ! ».
-« fond = new Décor() », entre fond et décor il faut choisir, on ne sait plus si l'objet est Fond ou Décor du coup.
-Chipotons : « Ecris cette commande, puis clique sur le bouton "Exécuter" »
devrait être : « Écris cette commande, puis clique sur le bouton « Exécuter ». ».
-Mineur : quand on exécute une commande, le mode construction disparaît brutalement.
-On a l'impression qu'après un Ctrl + S sur la « console », l'enregistrement se fera sur notre dernier fichier ouvert alors que ces parties sont indépendantes. À propos, l'édition de ces fichiers est désagréable puisque l'exécution fait basculer automatiquement vers un autre écran.

**Comment by LiaOkami** [comment]
Several remarks aren't relevant anymore. You should make an update on this list.

**Comment by ThomasTel** [comment]
None of this remarks are relevant anymore. Thanks to have answered, I close this issue.
