### ISSUE TITLE
Messages d'erreur

### ISSUE THREAD

**Issue by ThomasTel** [colombbus/tangara-client#45]
-« dir.ajouterCommande("droite", bob.avancer(10)) »
retourne « {0} n'est pas une commande valide ».
-« bob = new Robot(); bob.taille » ne retourne pas d'erreur.

**Comment by LiaOkami** [comment]
What is dir in the first command ?
For the second command, this is correct so it doesn't have to return an error.

**Comment by ThomasTel** [comment]
....What is dir in the first command ?
A CommandesClavier.

....For the second command, this is correct so it doesn't have to return an error.
It is correct in Javascript but I don't think it is in the philosophy of Declick to allow users to access or create undefined attributes.

**Comment by LiaOkami** [comment]
First issue moved to declick-client.
https://github.com/colombbus/declick-client/issues/6

Second issue is a duplicate of this one
https://github.com/colombbus/declick-client/issues/2
