### ISSUE TITLE
[Declick] Bob et le décor

### ISSUE THREAD

**Issue by ThomasTel** [colombbus/tangara-client#50]
En suivant le tutoriel, Bob, après être tombé, se retrouve derrière le décor.
Ça peut-être perturbant si l'on ne devine pas que l'ordre d'apparition sur l'écran (la couche de calque) dépend de l'ordre d'apparition dans le code.

**Comment by LiaOkami** [comment]
The tutorial has been removed, so this is not an issue anymore.
