### ISSUE TITLE
Appui en continu pour avancer

### ISSUE THREAD

**Issue by ThomasTel** [colombbus/tangara-client#51]
Le personnage peut continuer à avancer un bout de temps si on est
resté appuyé sur la touche attribuée suffisamment longtemps.

**Comment by LiaOkami** [comment]
Which character / key are you speaking about ? Please detail this issue.

**Comment by ThomasTel** [comment]
I was talking about commands like the following ones:
direction = new CommandesClavier();
direction.ajouterCommande("droite", "bob.avancer()");
which induce a continuous movement of the character.
I considered it as an abnormal behaviour but it appeared to be correct.
Indeed, we need to add a "rest command" to see the character stops.
