### ISSUE TITLE
Robot non effacé

### ISSUE THREAD

**Issue by ThomasTel** [colombbus/tangara-client#52]
C'est probablement lié à la synchronicité mais après réaffectation : 
bob = new Robot()
bob.avancer(300)
bob = new Robot()
Le premier robot n'est pas effacé.

**Comment by bonpra** [comment]
Aujourd'hui, Tangara ne contrôle si un nom est déjà utilisé avant de l'attribuer à une instance. Si tel est le cas, le premier objet nommé n'est plus accessible
