### ISSUE TITLE
SynchronousManager - Problem on first execution

### ISSUE THREAD

**Issue by LiaOkami** [colombbus/tangara-client#62]
In the FIRST execution of commands, SynchronousManager doesn't seems to have any effect.
However, it works after, no matter the number of executions.

Here is a simple code that shows the problem : 
bob = new Robot()
bob.avancer()
bob.descendre()

**Comment by bonpra** [comment]
Fixed for Robot: cf commit e6021bb84e000a2040841ca7f383f295d783c81d
Fixed for Turtle: cf commit deb1677e56ee054d15c13179287c7d13f015246b
