### ISSUE TITLE
Commande synchrone dans le start

### ISSUE THREAD

**Issue by ThomasTel** [colombbus/tangara-client#66]
Une commande synchrone (bob.avancer()) dans le start rend l'affichage des erreurs (exemple : "toto = new Truc()", une erreur qui n'est pas détectée au parsage) impossible.
En effet, cela est dû à au bloc try/catch de l'interpréteur qui gère les erreurs "de manière asynchrone" (puisque Javascript fonctionne en asynchrone).
Grosso modo :
try {
  //_1_, qui dure longtemps
}
catch {
  //est lancé avant la fin de _1_, Javascript asynchrone
}

**Comment by bonpra** [comment]
Fixed, cf 9a25cdfaf94a446a6f0d35e34b6ac1ec832cdaf5
