### ISSUE TITLE
Deux exercices ouverts dans le navigateur

### ISSUE THREAD

**Issue by ThomasTel** [colombbus/tangara-client#67]
En ayant deux exercices en cours d'édition ouverts, de nombreux bugs se profilent.
Après chargement de l'exercice d'id 1 (learn.html#1), on peut par exemple avoir le starter du 1 avec le checker du 3 ou encore le starter et le checker du 3, suivant les enregistrements de fichiers que l'on fait dans l'éditeur.

**Comment by LiaOkami** [comment]
This is corrected in declick-client.
