### ISSUE TITLE
tangara.loadProgram() doesn't work

### ISSUE THREAD

**Issue by Neonunux** [colombbus/tangara-client#72]
Régis = new Héros()
Régis.avancer(50)
Régis.ajouterBloc(arrièrePlan)

direction = new CommandesClavier()
direction.ajouterCommande("droite", "Régis.avancer()")
direction.ajouterCommande("gauche", "Régis.reculer()")
direction.ajouterCommande("haut", "Régis.monter()")
direction.ajouterCommande("bas", "Régis.descendre()")
direction.ajouterCommandeRepos("Régis.arrêter()")

sortie = new Animation("porte.png")
sortie.rendreTransparent("blanc")
sortie.définirPosition(819,218)
sortie.siCollisionAvec(Régis, "tangara.chargerProgramme('nouveau 2')") // marche po

**Comment by bonpra** [comment]
Fixed (f177eda5df56f40ba5c5f3bd38311824d5e54be1)
