### ISSUE TITLE
Robot - Collision

### ISSUE THREAD

**Issue by LiaOkami** [colombbus/tangara-client#73]
When Robot collide with a Block, it vibrates and doesn't want to stop.
It prevents the execution of further commands because it is stuck on one command.

**Comment by bonpra** [comment]
Fixed, cf d879e53421ce25dc4bb66376756f81c15dbb3959

**Comment by LiaOkami** [comment]
New problems appeared with the fix.

**Comment by LiaOkami** [comment]
All problems are fixed.
